cert-manager:
  installCRDs: true
  global:
    leaderElection:
      namespace: cert-manager

  prometheus:
    enabled: true

  resources:
    requests:
      cpu: 200m
      memory: 256Mi

  serviceAccount:
    create: true
    name: cert-manager
    annotations:
      azure.workload.identity/use: "true"
