apiVersion: v2
name: velero
description: Velero backup for Kubernetes
type: application

version: 0.1.0

dependencies:
  - name: velero
    version: 11.3.2
    repository: https://vmware-tanzu.github.io/helm-charts
