apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/DocFitz/testAKS.git
    targetRevision: dev
    path: apps/kyverno-policies
#notice no helm path here - using kustomization
  destination:
    server: https://kubernetes.default.svc
# no namespace since universally installed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

