namespace: demo-echo
replicas: 1

image:
  repository: ealen/echo-server
  tag: "0.9.2"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 80

gateway:
  name: main
  namespace: gateway-system
  sectionName: http

hostnames:
  - echo-prod.example.com
