namespace:
  create: true
  name: gateway-system

gateway:
  name: main
  gatewayClassName: cilium
  allowedRoutes:
    from: All

  tls:
    enabled: false
    secretName: ""

gateway:
  tls:
    enabled: true
    secretName: echo-prod-tls
