apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  source:
    repoURL: https://github.com/DocFitz/testAKS.git
    targetRevision: dev
    path: apps/kyverno-policies
# notice no helm values here using kustomization for policies
  destination:
    server: https://kubernetes.default.svc
# no namespace because these are universally applied
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

