apiVersion: v2
name: argocd
description: Argo CD (wrapper chart for GitOps)
type: application
version: 0.1.0

dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 9.4.2
